### ISSUE TITLE
Implement commands for restoring Instances

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-tools#18]
## Description
In Altinn/altinn-studio#3872 we have defined a backup architecture that uses Cosmos change feed and a azure function to backup data to a blob storage.

We need to create procedure and tools to help restore data

Possible scenarios

- End user has deleted one or several dataelements by mistake. We need to recover data from cosmos db and blob storage
- A bug in app has corrupted all data in a given periode for a app
- Service owners has overwritten data inputed by the user. 

## Considerations
- Batch functionality
- Access tokens from tools?
- Console or web-based tools?
- Redo
- Who is authorized to run it

## Acceptance criteria
- We should have a process and tools available to restore blob data to a given time based on specific criteria.  

## Specification tasks
- [ ] Workshop with team to identify needs
- [ ] Define process 
- [ ] Define tools needed

## Suggested commands
![image.png](https://images.zenhubusercontent.com/5c8f655333fd990b927f5ea1/4d46c47d-681e-4e1d-8f1e-8eec2415b8cb)

## Development tasks
- [ ] Develop tools

**Comment by SandGrainOne** [comment]
Storage will no longer be using CosmosDB and the CosmosDB document backup will be turned off.
